version: "2"
services:
  client:
    build: .
    volumes:
      - ./:/app/
    working_dir: /app/
    command: python3 -u client.py

  model_owner:
    build: .
    volumes:
      - ./:/app/
    working_dir: /app/
    command: python -u model_owner.py

  # serv1:
  #   build: .
  #   volumes:
  #     - ./app:/app/
  #   working_dir: /app/
  #   command: python serv.py
  #   environment:
  #     - PORT=4000

  # serv2:
  #   build: .
  #   volumes:
  #     - ./app:/app/
  #   working_dir: /app/
  #   command: python serv.py
  #   environment:
  #     - PORT=4001

  # serv2:
  #   build: .
  #   volumes:
  #     - ./app:/app/
  #   working_dir: /app/
  #   command: python serv.py
  #   environment:
  #     - PORT=4002
