version: "2"
services:
  client:
    build: .
    volumes:
      - ./:/app/
    working_dir: /app/
    command: python3 -u client.py

  model_owner:
    build: .
    volumes:
      - ./:/app/
    working_dir: /app/
    command: python -u model_owner.py

  serv0:
    build: .
    volumes:
      - ./:/app/
    working_dir: /app/
    command: python serv.py
    environment:
      - NUMBER=0

  serv1:
    build: .
    volumes:
      - ./:/app/
    working_dir: /app/
    command: python serv.py
    environment:
      - NUMBER=1

  serv2:
    build: .
    volumes:
      - ./:/app/
    working_dir: /app/
    command: python serv.py
    environment:
      - NUMBER=2
